### PR TITLE
C hypothesis

### PR DESCRIPTION
**Pull request by cdwijs**
Fixed compiling errors on windows 7, Qt 5.10.0 and mingw530_32
Added windows devel guide

### CODE REVIEW

**Comment by JohnAGoldsmith** [comment]
This should help when we create a Windows version.

**Comment by cdwijs** [comment]
Hi John,
I don't understand. The changes I made are enough to have a working version that compiles an runs on Windows. The only thing missing is an installer for the windows version.
Are the changes I made harmful for the Linux version? Is there another reason not to merge?
Kind regards,
Cedric

**Comment by JohnAGoldsmith** [comment]
I'm sorry, I don't remember what you're referring to. I believe I did
accept your request to merge. It sounds like you understood me as saying
something critical of your suggestion, but I don't have any recollection of
that.
Sincerely,
John Goldsmith

**Comment by cdwijs** [comment]
Hi John,
Thank you for your reply.
My apologies, English is not my first language. it looks to me you closed the merge request without merging.
If you look at my version, there's the file DEVEL-WINDOWS.txt
https://github.com/cdwijs/QtLing/tree/CHypothesis
If I look at your version, the file DEVEL-WINDOWS.txt is not present:
https://github.com/JohnAGoldsmith/QtLing

Do you want me to re-create the pull request, or can you try again to merge my changes?
Cheers,
Cedric

**Comment by JohnAGoldsmith** [comment]
Yes, do recreate the pull request -- unless you know how I can go back and accept the older one.
John Goldsmith

**Pull request closed without merging**
